### PR TITLE
Patch connect request

### PR DESCRIPTION
**Pull request by benjaminbollen**

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
@rossmuir Can you check this PR, whether it improves bootstrapping time compared to master

**Comment by benjaminbollen** [comment]
The failed test is an intermittant failure in deprecated Routing::sentinel

**Comment by benjaminbollen** [comment]
Will re-open with MAID-1105 in branch title

**Pull request closed without merging**
