### PR TITLE
addresses warnings -- Relates to issue 300

### PR DESCRIPTION
**Pull request by mmoadeli**
addresses issue  https://github.com/maidsafe/routing/issues/300

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/302)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by rossmuir** [comment]
Could `#![forbid(bad_style, warnings)] ` be added to `lib.rs` please to ensure no more slip in after your good work - cheers

**Comment by inetic** [comment]
Looks good to me, @mmoadeli, let me know if you're gonna add what @rossmuir asked for and I'll do the merge.

**Comment by mmoadeli** [comment]
@inetic I am trying to add that. Just investigating if it really works. just 5 min

**Comment by mmoadeli** [comment]
done @inetic & @rossmuir . Had to be added in routing.rs example separately.

**Comment by benjaminbollen** [comment]
thanks mahmoud

**Pull request merged**
