### PR TITLE
Examples updates

### PR DESCRIPTION
**Pull request by Viv-Rajkumar**
Addition to PR #857 

- Fixed key_value example build
- ~~Added ci_test example run to travis runs~~
- example client waits for Connected event from routing before returning from new fn.
- Disabled log4rs usage. Currently stalls the example on OSX with accurate loggers

TODO:
Response handling to prevent race conditions caused during churn affecting the output of Get requests

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/858)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Nice work @Viv-Rajkumar  :+1:

**Comment by dirvine** [comment]
I am happy to merge if that works for you, we can deal with the todo next year :-)

**Comment by Viv-Rajkumar** [comment]
Main thanks to @ustulation for this one. haha cool yep would be worth merging this and continuing from master.

**Pull request merged**
