### PR TITLE
chore/all: Fix remaining Clippy warnings.

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/995)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @brian-js

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/types.rs, line 80 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/995#-KGGjkj6c0sMKxwy6pEs:-KGGjkj6c0sMKxwy6pEt:-858136266) ([raw file](https://github.com/maidsafe/routing/blob/57aa140b6aadd34545efb4c53154ec404e0afc47/src/types.rs#L80)):*
Probably means patch version change here

---

*[tests/ci.rs, line 480 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/995#-KGGjx-2xTgyHxfrPvn4:-KGGjx-2xTgyHxfrPvn5:920222652) ([raw file](https://github.com/maidsafe/routing/blob/57aa140b6aadd34545efb4c53154ec404e0afc47/tests/ci.rs#L480)):*
Be nice to see more of this `attack on the clones()` :-) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/995)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/types.rs, line 80 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/995#-KGGjkj6c0sMKxwy6pEs:-KGGkwxvzpUFb8CNT-uI:893265904) ([raw file](https://github.com/maidsafe/routing/blob/57aa140b6aadd34545efb4c53154ec404e0afc47/src/types.rs#L80)):*
But that's not urgent, is it? We don't need that impl anywhere else currently.
(I'd also be okay with `allow`ing missing `Default` implementations ...)

---

*[tests/ci.rs, line 480 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/995#-KGGjx-2xTgyHxfrPvn4:-KGGlCMpCkaT2gJZGp-A:-510466975) ([raw file](https://github.com/maidsafe/routing/blob/57aa140b6aadd34545efb4c53154ec404e0afc47/tests/ci.rs#L480)):*
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/995)*

**Comment by dirvine** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/types.rs, line 80 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/995#-KGGjkj6c0sMKxwy6pEs:-KGGmD9Bl0Ks105BMgPb:-1925187712) ([raw file](https://github.com/maidsafe/routing/blob/57aa140b6aadd34545efb4c53154ec404e0afc47/src/types.rs#L80)):*
No not urgent, but may help clean up some code in vaults perhaps? well picky really, just we can default rather than call ::new() so trivial.  Poss patch though ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/995)*

**Pull request merged**
