### PR TITLE
Peer manager refactor

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1084)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 2 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[src/core.rs, line 1055 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMSy2p01IOhIi0DoSPx:-KMSy2p01IOhIi0DoSPy:-2056584875) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/core.rs#L1055)):*
> ```Rust
>             self.dropped_tunnel_node(&peer_id);
>         } else {
>             let _ = self.peer_mgr.remove_peer(&peer_id);
> ```

Can it actually be anything else than the bootstrap connection? Could this line be omitted entirely?

---

*[src/core.rs, line 1585 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMSzEZkaU2U-i7urQl3:-KMSzEZkaU2U-i7urQl4:-85617957) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/core.rs#L1585)):*
> ```Rust
>             Some(close_group) => close_group,
>             None => return Err(RoutingError::InvalidDestination),
>         };
> ```

You could also avoid the duplicated `close_group` variable:
`let close_group = try!(self.peer_mgr.routing_table().close_nodes(&dst_name, GROUP_SIZE).ok_or(|_| RoutingError::InvalidDestination));`
(Not sure whether that's better - your call.)

---

*[src/core.rs, line 2289 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT-gMkIp995bVL1ywP:-KMT-gMl0tYJsbKl2cUp:-1995019043) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/core.rs#L2289)):*
> ```Rust
>                     Some(dst_pub_id) => Some((dst_peer_id, *dst_pub_id)),
>                     None => None,
>                 }
> ```

Or:
`self.peer_mgr.get_communicating_peer(&dst_peer_id).map(|dst_pub_id| (dst_peer_id, *dst_pub_id))`?

---

*[src/peer_manager.rs, line 230 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT0TfV9dEQYnOmsajd:-KMT0TfWUTf3p9UpoV8Q:194346640) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L230)):*
> ```Rust
>     }
> 
>     pub fn is_tunnel(&self, peer_id: &PeerId, dst_id: &PeerId) -> bool {
> ```

Looks like this is just testing whether both are in the routing table. Maybe it should be renamed - or even just take one argument and check whether that is in the routing table. The caller would then call it twice, with both IDs, if needed.

---

*[src/peer_manager.rs, line 351 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT0oipHsERJBlc5fMa:-KMT0oiqyOnMPhv3TF1Z:-2069039602) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L351)):*
> ```Rust
>         self.pub_id_map.get(peer_id).and_then(|pub_id| {
>             match self.get_state(pub_id) {
>                 Some(&PeerState::CrustConnecting) => Some(pub_id),
> ```

... or _would_ it actually make sense (at the call site in core.rs) to consider these other three states here, too?

---

*[src/peer_manager.rs, line 357 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT14D_D0STwOrSEqkV:-KMT14D_D0STwOrSEqkW:1485630135) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L357)):*
> ```Rust
>     }
> 
>     /// Return the first peer_id of the peer_node bearing the name.
> ```

I'd use either `peer ID` or `` `PeerId` `` in comments. `peer_id` is just a common variable name, but neither the type nor a natural language term. (And maybe just `node` instead of `peer_node`. Also elsewhere.)

---

*[src/peer_manager.rs, line 372 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT1ziZi6xEtJy5EWNA:-KMT1ziZi6xEtJy5EWNB:-509987281) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L372)):*
> ```Rust
>             })
>             .collect()
>     }
> ```

It would be nice to get rid of these two methods: Ideally we should try to always address nodes by their public ID instead of their peer ID, where possible.
But if it _isn't_ possible, and this needs to be done very often, it might make sense to include the peer ID in the `node_map` instead, so we don't need to iterate here and can just look up that entry.

Similarly with `get_pub_ids`: I think in general, we should try to reduce the number of types by which we need to look up peers. And for those types that _need_ to be used as indices, we should consider additional maps, etc.

(I'm fine with leaving all of these as is for this PR, just something to keep in mind.)

---

*[src/peer_manager.rs, line 387 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT3Qwp7yTYpod8xTut:-KMT3Qwp7yTYpod8xTuu:-1806396749) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L387)):*
> ```Rust
> 
>     /// Returns the public ID of the given peer, if it is in `Connected` or `Tunnel` state.
>     pub fn get_communicating_peer(&self, peer_id: &PeerId) -> Option<&PublicId> {
> ```

Maybe `get_routing_peer`? Or `get_connected_or_tunnelling_peer`? Or `get_routing_table_entry`? Not sure ...

---

*[src/peer_manager.rs, line 397 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT3fB_u4Ef_JJfNyQe:-KMT3fB_u4Ef_JJfNyQf:898019980) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L397)):*
> ```Rust
>     }
> 
>     /// Sets the given peer to state `SearchingForTunnel` or returns `false` if it doesn't exist.
> ```

That comment is wrong now.

---

*[src/peer_manager.rs, line 530 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT3zT_fkUoAP35qXs5:-KMT3zT_fkUoAP35qXs6:1641074428) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L530)):*
> ```Rust
>     }
> 
>     /// Removes the given entry.
> ```

That should also describe what the complicated return value means now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by maqi** [comment]
*[src/peer_manager.rs, line 351 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT0oipHsERJBlc5fMa:-KMTJ-gNFVfpVzh3wZP9:-1084921857) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L351)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> ... or _would_ it actually make sense (at the call site in core.rs) to consider these other three states here, too?
</details>
don't get what you mean.
this function only being called by core once, when there is a `connect_failure`, which the other three states shall not trigger/incur any further handling?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[src/peer_manager.rs, line 351 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT0oipHsERJBlc5fMa:-KMTJv0e-Qpe8JXeL848:623082494) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L351)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> don't get what you mean.
> this function only being called by core once, when there is a `connect_failure`, which the other three states shall not trigger/incur any further handling?
</details>
Ah, right, that can only happen in `CrustConnecting` state, of course. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by maqi** [comment]
*[src/core.rs, line 1585 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMSzEZkaU2U-i7urQl3:-KMcMg0fLmgaT-WfnBJa:1453488304) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/core.rs#L1585)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> You could also avoid the duplicated `close_group` variable:
> `let close_group = try!(self.peer_mgr.routing_table().close_nodes(&dst_name, GROUP_SIZE).ok_or(|_| RoutingError::InvalidDestination));`
> (Not sure whether that's better - your call.)
</details>
the new approach will have the same lines after rustfmt.
so prefer the current approach as it is more readable   :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by maqi** [comment]
*[src/peer_manager.rs, line 230 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT0TfV9dEQYnOmsajd:-KMcMzpoFAPSvxpRjoX8:2140413627) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L230)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Looks like this is just testing whether both are in the routing table. Maybe it should be renamed - or even just take one argument and check whether that is in the routing table. The caller would then call it twice, with both IDs, if needed.
</details>
prefer avoiding force the caller call twice, and handle everything inside peer_manager.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by maqi** [comment]
*[src/core.rs, line 1055 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMSy2p01IOhIi0DoSPx:-KMcP2Us4t-rlA7bURZK:-308380246) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/core.rs#L1055)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Can it actually be anything else than the bootstrap connection? Could this line be omitted entirely?
</details>
not sure about this. if in `client` mode (working as client), does it still have chance of losing a peer?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core.rs, line 1055 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMSy2p01IOhIi0DoSPx:-KMcdRD-s3TEzWd4PRmx:-2070335952) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/core.rs#L1055)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> not sure about this. if in `client` mode (working as client), does it still have chance of losing a peer?
</details>
Only the proxy node, I think.
That should be very evident from the code once #1080 is merged.

---

*[src/peer_manager.rs, line 230 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT0TfV9dEQYnOmsajd:-KMceT7yWbtjF1kHP2cU:-1922612720) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L230)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> prefer avoiding force the caller call twice, and handle everything inside peer_manager.
</details>
OK. But it should probably still have a more descriptive name. `can_tunnel_for`?

---

*[src/peer_manager.rs, line 357 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMT14D_D0STwOrSEqkV:-KMcfFDYhWU98Tpifuht:-198242898) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/peer_manager.rs#L357)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> I'd use either `peer ID` or `` `PeerId` `` in comments. `peer_id` is just a common variable name, but neither the type nor a natural language term. (And maybe just `node` instead of `peer_node`. Also elsewhere.)
</details>
(Also below in `get_peer_ids`, `get_pub_ids`, etc.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by maqi** [comment]
*[src/core.rs, line 1055 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1084#-KMSy2p01IOhIi0DoSPx:-KMd4KILhw4pD7aO3y0c:-364590736) ([raw file](https://github.com/maidsafe/routing/blob/4e7189e3c7bc77eb1bb6c18c32c32a41397eb1b8/src/core.rs#L1055)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Only the proxy node, I think.
> That should be very evident from the code once #1080 is merged.
</details>
tested with this line removed and passed all the current tests.
will include the removal in the PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1084)*

**Pull request merged**
