### PR TITLE
Counteract message convergence

### PR DESCRIPTION
**Pull request by afck**
This implements the remainder of the RFC:
https://github.com/maidsafe/rfcs/blob/master/active/0019-new-kademlia-routing-logic/0019-new-kademlia-routing-logic.md
Messages that are received multiple times are also rerouted multiple times, up to `PARALLELISM`.

Also deduplicates some code.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/904)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @brian-js

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
The tests pass now, but only after I retried the OS X and 32-bit Windows ones. On OS X it was the open file count issue, but on Windows it actually panicked. I'll try to find out more tomorrow.

**Comment by afck** [comment]
I reran the tests a few times locally and on Appveyor and they all passed.

**Pull request merged**
