### PR TITLE
routing tests.

### PR DESCRIPTION
**Pull request by brian-js**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/943)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core_tests.rs, line 134 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNtp_eSqO7TZI7MIXC:-KDNtp_eSqO7TZI7MIXD:-1564683631) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L134)):*
Wouldn't `try!(self.action_tx.send(action))` do the same thing?

---

*[src/core_tests.rs, line 415 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNxTnFhwz6d4OhC5GH:-KDNxTnGF7-YuLw70vnS:-1209675122) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L415)):*
Is this really a requirement, i. e. can't it ever be correct to have routing table size 16 with 20 nodes?
Also, I think the checks for the Kademlia invariant make this one unnecessary.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/943)*

**Comment by brian-js** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core_tests.rs, line 134 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNtp_eSqO7TZI7MIXC:-KDO-6foPT0bY5kQ6_8E:1533539367) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L134)):*
No. It needs a semi-colon after it followed by Ok(()), or similar.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/943)*

**Comment by brian-js** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core_tests.rs, line 415 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNxTnFhwz6d4OhC5GH:-KDO-rOzqTES1l-l6plY:-727697853) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L415)):*
Fair enough, I based it on your Python 'estimated' calculation but can remove the test if it's not required.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/943)*

**Comment by brian-js** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core_tests.rs, line 415 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNxTnFhwz6d4OhC5GH:-KDO175faJKQuWVdmvKE:-1580974479) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L415)):*
Done now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/943)*

**Comment by afck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core_tests.rs, line 134 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNtp_eSqO7TZI7MIXC:-KDO00vXE4NR-2u9xRKl:-900156578) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L134)):*
Yes, but you have that `Ok(())` already anyway.

---

*[src/core_tests.rs, line 415 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNxTnFhwz6d4OhC5GH:-KDO0xI1dOKs_pZhc5_o:877609309) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L415)):*
Yes, that's just an expected value: It can still occasionally legitimately be lower, and we don't want our tests to fail in these cases.
:thumbsup: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/943)*

**Comment by brian-js** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core_tests.rs, line 134 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/943#-KDNtp_eSqO7TZI7MIXC:-KDO1xmc7u1Qcg8lBOB2:2095721391) ([raw file](https://github.com/maidsafe/routing/blob/b7ae3ad75315404e58cf5f3b5ef83265e12f94a8/src/core_tests.rs#L134)):*
Ok, this is done too.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/943)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/943)*

**Pull request merged**
