### PR TITLE
Maid 1547

### PR DESCRIPTION
**Pull request by brian-js**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/890)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Looks good to me, but I think it should also test that `signed_message.check_integrity().is_err()` if the signature is wrong. You could change the `signature` field at the end of `signed_message_check_integrity` and assert that.

**Comment by brian-js** [comment]
^^^ Done.

**Comment by afck** [comment]
That's weird; do you know why the test suddenly failed in the doc examples on Travis? Doesn't seem to have anything to do with this change ... but maybe we should call that variable `_receiver` then?

**Comment by brian-js** [comment]
Looks like it arbitrarily decides to enforce checks. receiver and node both look like the culprits.

**Pull request merged**
