### PR TITLE
Example032

### PR DESCRIPTION
**Pull request by benjaminbollen**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/624)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
raised issue for intermittent failure in authority test (which has option to show intermittent failures for bad parameters in test) https://github.com/maidsafe/routing/issues/625

**Comment by dirvine** [comment]
I believe those tests will (like routing table tests) need to run X times allowing Y failures really. Even then we could get Y failures and still within bounds (random bah!).

**Pull request merged**
