### PR TITLE
refactor/states: merge JoiningNode and Node states

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1106)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/states/node.rs, line 319 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1106#-KNg-iNTLdb-KsN3TWn5:-KNg-iNU4G0UGrPR8V4g:-93493027) ([raw file](https://github.com/maidsafe/routing/blob/82c622999961beef998a5051d0c69276ea5299d5/src/states/node.rs#L319)):*
> ```Rust
>                 error!("{:?} Failed to start listening.", self);
>                 self.send_event(Event::Terminate);
>                 Transition::Terminate
> ```

You could `return Transition::Terminate` here and only have _one_ `Transition::Stay` at the end of the method. The stats shouldn't change on `ListenerFailed` anyway.

---

*[src/states/node.rs, line 1814 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1106#-KNg2YU8_x0hK-X7FcqA:-KNg2YU8_x0hK-X7FcqB:1529811798) ([raw file](https://github.com/maidsafe/routing/blob/82c622999961beef998a5051d0c69276ea5299d5/src/states/node.rs#L1814)):*
> ```Rust
>         }
> 
>         result
> ```

You could just `||` these two conditions and get rid of the local `result` variable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Comment by madadam** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/states/node.rs, line 1814 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1106#-KNg2YU8_x0hK-X7FcqA:-KNg73ojXk2pyBGXLQE6:-233772088) ([raw file](https://github.com/maidsafe/routing/blob/82c622999961beef998a5051d0c69276ea5299d5/src/states/node.rs#L1814)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> You could just `||` these two conditions and get rid of the local `result` variable.
</details>
I can't, because that would short-circuit the evaluation. I need both methods to be always called, no matter what they return. There might be a cleaner way to express this though...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/states/node.rs, line 319 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1106#-KNg-iNTLdb-KsN3TWn5:-KNg8jcykW2fVxQ6m6xN:-1746689084) ([raw file](https://github.com/maidsafe/routing/blob/82c622999961beef998a5051d0c69276ea5299d5/src/states/node.rs#L319)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> You could `return Transition::Terminate` here and only have _one_ `Transition::Stay` at the end of the method. The stats shouldn't change on `ListenerFailed` anyway.
</details>
(This way is fine, too, of course. Your call.)

---

*[src/states/node.rs, line 1814 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1106#-KNg2YU8_x0hK-X7FcqA:-KNg8Z401gt2KGf2ferw:1971293607) ([raw file](https://github.com/maidsafe/routing/blob/82c622999961beef998a5051d0c69276ea5299d5/src/states/node.rs#L1814)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> I can't, because that would short-circuit the evaluation. I need both methods to be always called, no matter what they return. There might be a cleaner way to express this though...
</details>
Ah, right. You could use `|` for that, of course, but let's not go down that road! :-D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Comment by maqi** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Comment by madadam** [comment]
Review status: 14 of 15 files reviewed at latest revision, all discussions resolved.

---

*[src/states/node.rs, line 1814 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1106#-KNg2YU8_x0hK-X7FcqA:-KNgJtCi32nzjhV_R8gi:-1351927613) ([raw file](https://github.com/maidsafe/routing/blob/82c622999961beef998a5051d0c69276ea5299d5/src/states/node.rs#L1814)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Ah, right. You could use `|` for that, of course, but let's not go down that road! :-D
</details>
Yeah, I feel that would be even more confusing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Comment by afck** [comment]
Closing and reopening to restart AppVeyor and Travis.

**Comment by afck** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1106)*

**Pull request merged**
