### PR TITLE
Minor core.rs refactoring

### PR DESCRIPTION
**Pull request by afck**
Apply clippy and rustfmt, and split up some methods.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/903)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Can you please check CI, the branches cannot be merged now with failing tests. Thx @afck

**Comment by afck** [comment]
Sorry!
They pass now.

**Comment by dirvine** [comment]
No worries, thx @afck

**Comment by dirvine** [comment]
Reviewed 1 of 6 files at r1, 1 of 1 files at r2.
Review status: 2 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/903)*

**Comment by dirvine** [comment]
Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/903)*

**Pull request merged**
