### PR TITLE
Issue 330

### PR DESCRIPTION
**Pull request by benjaminbollen**
#330

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
r? @dirvine

---

Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- src/message_header.rs @ r1
- src/routing_membrane.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/331)

**Comment by benjaminbollen** [comment]
relayed node now handles ConnectResponse and adds to RT, but the NewConnection precedes this, so is not marked 'online' in RT at requester side (it is marked online at responder side). 

This will block a third node as the RT's of 1 and 2 are online and offline respectively marked

**Comment by benjaminbollen** [comment]
Pausing here for tonight and making PR that removes the old routing node for publish

**Pull request merged**
