### PR TITLE
Our authority

### PR DESCRIPTION
**Pull request by benjaminbollen**
tests not checked, as last remaining compilation errors still to be resolved

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/478)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
Important points:
1. ClientManager(NameType) always points to the ClientName, not the element of the message
2. removed OurCloseGroup as Refresh messages will be handled without Authority (only valid when received from our RT)
3. updated the tests to refactor
4. excluded false positive from NaeManager (for ManagedNode)
5. updated documentation

**Comment by benjaminbollen** [comment]
6. also for NodeManager(NameType) points to the Node name, not the element

**Comment by dirvine** [comment]
I think that's good as these all have the address that shows why they are that authority, so it == element or nodendame etc. but whichever the authority address is quite explicit, so we do not need to work out outside this method if the name == element or node or client etc.

**Pull request merged**
