### PR TITLE
Fixes #369

### LINKED ISSUE #369: Enforce lint checks
Add the following lint checks to `lib.rs` (crust is a good example to check)
```
#![deny(deprecated, improper_ctypes, missing_docs, non_shorthand_field_patterns,
overflowing_literals, plugin_as_library, private_no_mangle_fns, private_no_mangle_statics,
raw_pointer_derive, stable_features, unconditional_recursion, unknown_lints, unsafe_code,
unsigned_negation, unused, unused_allocation, unused_attributes, unused_comparisons,
unused_features, unused_parens, while_true)] 

#![warn(trivial_casts, trivial_numeric_casts, unused_extern_crates, unused_import_braces,
unused_qualifications, variant_size_differences)]
```

### PR DESCRIPTION
**Pull request by brian-js**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/709)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @benjaminbollen

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
Pretty freaking awesome @brian-js ! Thank you and congratulations on crunching through it so fast.

**Comment by brian-js** [comment]
Thanks @benjaminbollen.

**Comment by rossmuir** [comment]
Cheers @brian-js

**Pull request merged**
