### PR TITLE
refactor/core_tests: Use real Node and Client in tests

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1055)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/client.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1055#-KKO-evderZ1LEGzNKkb:-KKO-everA8VDJoUSe7F:43736998) ([raw file](https://github.com/maidsafe/routing/blob/6a5361a79b7a90a41f98c0ee16a1230de2769e58/src/client.rs#L192)):*
> ```Rust
>     #[cfg(feature = "use-mock-crust")]
>     fn receive_action_result<T>(&self, rx: &Receiver<T>) -> Result<T, InterfaceError> {
>         while self.poll() {}
> ```

Actually, should we even do that here? I think in most cases the test itself wants to control when to poll and when to check for events. And that would even allow us to merge the two implementations.

---

*[src/core_tests.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1055#-KKO0sKE7e4vZnS4iDjo:-KKO0sKE7e4vZnS4iDjp:-1854013164) ([raw file](https://github.com/maidsafe/routing/blob/6a5361a79b7a90a41f98c0ee16a1230de2769e58/src/core_tests.rs#L81)):*
> ```Rust
>         TestNode {
>             handle: handle,
>             node: node,
> ```

I wonder whether this (and `client` in `TestClient`) should be called `inner` ... or should (some of) the `node` variables below be renamed to `test_node` ... not sure. It's okay as is, too. Your call. :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1055)*

**Comment by madadam** [comment]
*[src/client.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1055#-KKO-evderZ1LEGzNKkb:-KKOBLPT0mXBrufS8umu:-1362570227) ([raw file](https://github.com/maidsafe/routing/blob/6a5361a79b7a90a41f98c0ee16a1230de2769e58/src/client.rs#L192)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Actually, should we even do that here? I think in most cases the test itself wants to control when to poll and when to check for events. And that would even allow us to merge the two implementations.
</details>
The problem with doing what you suggest is the way methods like `Node::name` work. The method creates a channel, then sends a message to `Core`, then `recv` on the channel to retrieve the result. So it hides the async internals of `Core` behind a sync interface. If we didn't `poll` before `recv`, the test would get stuck.

It all feels quite hacky, so I wouldn't mind at all to refactor it into more sensible design.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1055)*

**Comment by madadam** [comment]
*[src/core_tests.rs, line 81 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1055#-KKO0sKE7e4vZnS4iDjo:-KKODSL-lhJz83nig8h-:1411505674) ([raw file](https://github.com/maidsafe/routing/blob/6a5361a79b7a90a41f98c0ee16a1230de2769e58/src/core_tests.rs#L81)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> I wonder whether this (and `client` in `TestClient`) should be called `inner` ... or should (some of) the `node` variables below be renamed to `test_node` ... not sure. It's okay as is, too. Your call. :-)
</details>
Yeah, `inner` is probably better. I'll change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1055)*

**Comment by afck** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/client.rs, line 192 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1055#-KKO-evderZ1LEGzNKkb:-KKOLB-DdWZCWlxSyFfv:-960082980) ([raw file](https://github.com/maidsafe/routing/blob/6a5361a79b7a90a41f98c0ee16a1230de2769e58/src/client.rs#L192)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> The problem with doing what you suggest is the way methods like `Node::name` work. The method creates a channel, then sends a message to `Core`, then `recv` on the channel to retrieve the result. So it hides the async internals of `Core` behind a sync interface. If we didn't `poll` before `recv`, the test would get stuck.
> 
> It all feels quite hacky, so I wouldn't mind at all to refactor it into more sensible design.
</details>
Ugh, of course.
Then let's leave it as is for now: first the tests, then the refactoring.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1055)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1055)*

**Pull request merged**
