### PR TITLE
fix/examples: handle Terminate event

### PR DESCRIPTION
**Pull request by afck**
Also removes some unneeded cloning and hashing in the examples.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1072)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
@afck: no appropriate reviewer found, use r? to override

**Comment by Fraser999** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1072)*

**Pull request merged**
