### PR TITLE
feat/tests: randomise message handling order in mock crust

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1134)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
@afck: no appropriate reviewer found, use r? to override

**Comment by Fraser999** [comment]
Review status: 0 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mock_crust/support.rs, line 124 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1134#-KQuef8mcAOV8-Pq0Yru:-KQuef8mcAOV8-Pq0Yrv:b2xnse3) ([raw file](https://github.com/maidsafe/routing/blob/c962c98513b544ed707819f3a04bb07d524e927a/src/mock_crust/support.rs#L124)):*
> ```Rust
>         let mut network_impl = self.0.borrow_mut();
>         let keys: Vec<_> = network_impl.queue.keys().cloned().collect();
>         let (sender, receiver) = if let Some(key) = network_impl.rng.choose(&keys) {
> ```

Nice - I didn't know about `choose()` :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1134)*

**Comment by Fraser999** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1134)*

**Pull request merged**
