### PR TITLE
Fix minor issues with simple_key_value_store output, issue #316

### LINKED ISSUE #316: Minor issues with simple_key_value_store output
Once running, simple_key_value_store outputs:

>     Input command (stop, put <key> <value>, get <key>)

To keep this consistent with Crust example and docopt syntax it should be

    Enter command (stop | put <key> <value> | get <key>)>

<hr/>

Entering `put k v` and `get k` yield respectively:

>     putting data TestData( key: "k" , value: "v" ) to network with name as 8335fa..017c09
    getting data having key k from network using name as 8335fa..017c09

The outputs should have initial capital letters, and they should either both insert quotes round the key or neither should.  I'd prefer the output to be more like:

    Putting "v" to the network under key "k".
    Getting value for key "k" from network.

I don't think we should be showing the hex-encoded hash in the output - it's maybe useful for us to debug stuff, but it's confusing as part of an example.

### PR DESCRIPTION
**Pull request by rossmuir**
Fixed #316

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/327)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by rossmuir** [comment]
@Fraser999

**Comment by rossmuir** [comment]
@Fraser999 Sorry I will sort the conflicts tomorrow

**Pull request merged**
