### PR TITLE
Fix two spelling mistakes in the comments

### PR DESCRIPTION
**Pull request by adrianbrink**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/888)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @brian-js (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by dirvine** [comment]
Thanks very much :+1 
r? @dirvine

**Comment by adrianbrink** [comment]
@dirvine Is there a general overview document outlining the code base and the future roadmap, especially in regards to contributions?
Thanks.

**Comment by dirvine** [comment]
There is not at the moment (heavy refactor completing) I can tell you the issues we will be working on are 

1. A kademlia routing table issue (table population issue, but documenting in house atm)
2. Implementing direction checks for messages (ensure messages outside close groups are not being injected and are moving right direction)
3. Re-introduce an authority check (in git history called confirm_authority)

The main changes will be matching a new crust API that is being worked on this week. Stay tuned though as @afck and I will be creating a roadmap very soon for the lib. I would hope next week as this week will be frantic with crust changes). Thanks again for input though It is very much appreciated. 

A larger side project will be using the kadmelia_routing_table and xor_name crate to build a large simulator / analyser for routing. We have not even begun, but did a lot of work with oversim etc. and it's not enough. So building such a crate is on the horizon. It will allow us to test assumptions and make improvements.

**Pull request merged**
