### PR TITLE
Maid 1043 remove old sentinel

### PR DESCRIPTION
**Pull request by benjaminbollen**

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
Hold off merge until v0.1.60 has started; first two commits are from other PRs

**Comment by benjaminbollen** [comment]
good to be merged now

**Comment by inetic** [comment]
Would you like to check the "remove old sentinel" task?

**Comment by benjaminbollen** [comment]
I do the checking off in a separate PR normally

**Comment by inetic** [comment]
Aha, OK, I'll merge then.

**Pull request merged**
