### PR TITLE
appendable_data append tests; apply_wrapper function for priv_appendable_data

### PR DESCRIPTION
**Pull request by maqi**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1138)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Typo in the title: "appendable"

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/priv_appendable_data.rs, line 530 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1138#-KRS_TtN_MUcKTL07XQI:-KRS_TtN_MUcKTL07XQJ:b-or7c0b) ([raw file](https://github.com/maidsafe/routing/blob/c18d121c0dc966b914b6908509791cb8dca94d15/src/priv_appendable_data.rs#L530)):*
> ```Rust
>         let black_key = sign::gen_keypair();
>         let mut white_list = BTreeSet::new();
>         white_list.insert(white_key.0.clone());
> ```

This `clone` is unnecessary. Please check Clippy on Travis nightly on Linux if you can't run Clippy locally.

Also, `Filter::white_list` accepts any `IntoIterator`, so you don't have to create a `BTreeSet` first. You can e.g. call `Filter::white_list(Some(white_key.0))`. (Or probably`Filter::white_list([white_key.0])`?)

(Also in the black list and pub tests.)

---

*[src/priv_appendable_data.rs, line 541 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1138#-KRSaLSf-msaZRq6MWWy:-KRSaLSgDemJFJAiaJFa:b11oz88) ([raw file](https://github.com/maidsafe/routing/blob/c18d121c0dc966b914b6908509791cb8dca94d15/src/priv_appendable_data.rs#L541)):*
> ```Rust
>                                                                      Some(&keys.1)) {
>             Ok(priv_appendable_data) => priv_appendable_data,
>             Err(error) => panic!("Error: {:?}", error),
> ```

Maybe `unwrap!` would be more concise than `match`.

---

*[src/pub_appendable_data.rs, line 565 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1138#-KRSbA_8LtnIuIXLm0mK:-KRSbA_8LtnIuIXLm0mL:bcb33zh) ([raw file](https://github.com/maidsafe/routing/blob/c18d121c0dc966b914b6908509791cb8dca94d15/src/pub_appendable_data.rs#L565)):*
> ```Rust
> 
>         assert!(!pub_appendable_data.append(black_appended_data.clone()));
>         assert!(pub_appendable_data.append(white_appended_data.clone()));
> ```

It shouldn't be necessary to clone these.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1138#-:-KRSZkr0TakDHH8YJfTF:bi4rt87)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/append_types.rs, line 166 at r2](https://reviewable.io:443/reviews/maidsafe/routing/1138#-KRT7OWB2PWm89wgGOGF:-KRT7OWB2PWm89wgGOGG:b-kpmd4b) ([raw file](https://github.com/maidsafe/routing/blob/af55c922790e657720c8adea9fbb227b375cb16c/src/append_types.rs#L166)):*
> ```Rust
>     pub fn sign_key(&self) -> Option<&PublicKey> {
>         match *self {
>             AppendWrapper::Pub { .. } => None,
> ```

Shouldn't this return `self.data.sign_key`?

We should probably replace `append` with `apply_wrapper` in `PubAppendableData`, too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1138)*

**Comment by afck** [comment]
Thanks! Just some rustfmt and Clippy fixes and it should be good to merge.

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/append_types.rs, line 166 at r2](https://reviewable.io:443/reviews/maidsafe/routing/1138#-KRT7OWB2PWm89wgGOGF:-KRTW9mOvHpJvlFFgJ3l:b-dsj556) ([raw file](https://github.com/maidsafe/routing/blob/af55c922790e657720c8adea9fbb227b375cb16c/src/append_types.rs#L166)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Shouldn't this return `self.data.sign_key`?
> 
> We should probably replace `append` with `apply_wrapper` in `PubAppendableData`, too.
</details>
Now it can probably return `&PublicKey` instead of `Option<&PublicKey>`. And I think this `&` isn't needed, because it's already a reference.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1138#-:-KRTWfsKNgnU8fB1zt80:bvi2s7p)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/pub_appendable_data.rs, line 129 at r3](https://reviewable.io:443/reviews/maidsafe/routing/1138#-KRTY1i5mivIyKvDsDDv:-KRTY1i5mivIyKvDsDDw:bta5tpn) ([raw file](https://github.com/maidsafe/routing/blob/2922f7bff0dfacd08a1e4bd3e233d3f5ad494cb6/src/pub_appendable_data.rs#L129)):*
> ```Rust
>         if !wrapper.verify_signature() {
>             return false;
>         }
> ```

Actually, these should probably also compare the version: The wrapper's version needs to match the data version exactly. The new method should replace a large chunk of `handle_append` in https://github.com/maidsafe/safe_vault/pull/547/files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1138)*

**Comment by maqi** [comment]
there is a clippy error which complains having too many parameters for PrivAppendableData's constructor.
seems we have to stay with it now.  :(

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1138#-:-KRTjA4L0Q_QBooHHZR0:bhves1a)*

**Comment by afck** [comment]
Reviewed 3 of 3 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1138)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1138)*

**Pull request merged**
