### PR TITLE
version change to 0.3.1

### PR DESCRIPTION
**Pull request by benjaminbollen**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/587)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
test this please

**Comment by Viv-Rajkumar** [comment]
looks like the lib is building in all platforms Tests are in their same state as before with compile errors. merging this in to allow vaults and client to use the latest lib code

**Pull request merged**
