### PR TITLE
Expose new routing API

### PR DESCRIPTION
**Pull request by benjaminbollen**
1. we lose 15 unit tests for routing_node that need to be carried over
2. sad commit as it skews my github contribution line count

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/332)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 6 of 10 files reviewed, 1 unresolved discussion, some commit checks pending.
Reviewed files:
- Cargo.toml @ r1
- examples/routing.rs @ r1
- examples/simple_key_value_store.rs @ r1
- src/lib.rs @ r1
- src/routing_client.rs @ r1
- src/routing_client_new.rs @ r1

---

<sup>**[src/routing_client_old.rs, line 1 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/332#-JrUjPhS6JJyrNo9PjzG)** ([raw file](https://github.com/maidsafe/routing/blob/10c790ccae25ee0180445b0ac4670a377d8230c2/src/routing_client_old.rs#L1)):</sup>
Did we forget to rename this maybe ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/332)

**Comment by benjaminbollen** [comment]
Review status: 6 of 10 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/routing_client_old.rs, line 1 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/332#-JrUjPhS6JJyrNo9PjzG)** ([raw file](https://github.com/maidsafe/routing/blob/10c790ccae25ee0180445b0ac4670a377d8230c2/src/routing_client_old.rs#L1)):</sup>
I don't understand. probably too tired.  I have two commits; first renames 'default' to 'old', second 'new' to 'default'; though it would be safer for git to have two sequencial commits to avoid conflicts

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/332)

**Comment by dirvine** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- src/routing_client_old.rs @ r1
- src/routing_node.rs @ r1
- src/routing_node_new.rs @ r1
- src/routing_node_old.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/332)

**Pull request merged**
