### PR TITLE
Bump to version 0.1.60

### PR DESCRIPTION
**Pull request by benjaminbollen**

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
?r @inetic 

you can merge this after the patch for connect_requests has been merged

**Comment by benjaminbollen** [comment]
r? @inetic

you can merge this after the patch for connect_requests has been merged

**Pull request merged**
