### PR TITLE
fix/send: fix acks, test with prng, rename some events

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1044)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
@afck: no appropriate reviewer found, use r? to override

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 6 files at r3, 2 of 2 files at r4.
Review status: 3 of 13 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core.rs, line 2359 \[r4\]](https://reviewable.io:443/reviews/maidsafe/routing/1044#-KJyo9W7mD5i77GjulQn:-KJyo9W8-0PfIm8IiAAn:-1797932448) ([raw file](https://github.com/maidsafe/routing/blob/da8af7c910ad58ceb5f7ee954788199d6d987eb1/src/core.rs#L2359)):*
> ```Rust
>                            self,
>                            GROUP_SIZE - 1);
>                     let _ = self.event_sender.send(Event::RestartRequired);
> ```

maybe worth checking here if we are the first node and instead raise a Terminate event so the user running the vault can take corresponding action and not run their vault with the `-f` flag next time. Just restarting is gonna get vault(with routing) to start a new network.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1044)*

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 2 files at r1, 4 of 6 files at r2, 5 of 6 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1044)*

**Comment by afck** [comment]
Review status: 12 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core.rs, line 2359 \[r4\]](https://reviewable.io:443/reviews/maidsafe/routing/1044#-KJyo9W7mD5i77GjulQn:-KJz07t4ADixjRn-1rGJ:-499146009) ([raw file](https://github.com/maidsafe/routing/blob/da8af7c910ad58ceb5f7ee954788199d6d987eb1/src/core.rs#L2359)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> maybe worth checking here if we are the first node and instead raise a Terminate event so the user running the vault can take corresponding action and not run their vault with the `-f` flag next time. Just restarting is gonna get vault(with routing) to start a new network.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1044)*

**Comment by Viv-Rajkumar** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core.rs, line 2374 \[r5\]](https://reviewable.io:443/reviews/maidsafe/routing/1044#-KJz3zqZdSeA_JPz4a1F:-KJz3zq_w_VVOxxX3CUG:2094613341) ([raw file](https://github.com/maidsafe/routing/blob/5a9477863ae40f217bd6ced7374809b1b7638575/src/core.rs#L2374)):*
> ```Rust
>     }
> 
>     fn rebootstrap(&mut self) {
> ```

we still don't call `crust_service.disconnect()` to the currently connected peer(one we remove from peer_mgr) ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1044)*

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1044)*

**Comment by Viv-Rajkumar** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1044)*

**Pull request merged**
