### PR TITLE
Migrate to the new Crust API

### PR DESCRIPTION
**Pull request by afck**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/912)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
Merging this now. As noted in slack #routing however, this changeset does need an audit arranged too. Hopefully with adam's mock for crust in place tests should be able to validate the behaviour accurately too.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/912#-:-KBCc-EA8wgJQqRR5F7x:-1567527581)*

**Comment by Viv-Rajkumar** [comment]
Reviewed 22 of 22 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/912)*

**Pull request merged**
