### PR TITLE
refactor: simplify state machine construction

### PR DESCRIPTION
**Pull request by d1vyank**

### CODE REVIEW

**Comment by pierrechevalier83** [comment]
Sorry man: I hadn't seen your PR and merged mine first. This looks great! Thanks for all the PRs :D Mind rebasing? I'll merge it next

**Comment by d1vyank** [comment]
Done!

**Comment by d1vyank** [comment]
Not sure what causes the Windows build failure — any hints?
```
test mock_network::churn::messages_during_churn ... test mock_network::churn::messages_during_churn has been running for over 60 seconds
test mock_network::churn::messages_during_churn ... FAILED
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 8, kind: Other, message: "OS Error 8 (FormatMessageW() returned error 317)" }', src\libcore\result.rs:997:5
error: test failed, to rerun pass '--test mock_network_tests'
Command exited with code 101
```

**Comment by pierrechevalier83** [comment]
> Not sure what causes the Windows build failure — any hints?

I'm not sure either. I see only the Windows x86 build failed, so I'm gonna go with "probably a fluke".
I triggered a rebuild. If it fails, I'll look deeper into it :smile:

**Pull request merged**
