### PR TITLE
fix/peer_manager: fix removal of expired peers and tokens

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1122)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/peer_manager.rs, line 809 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1122#-KOF-ZloMFn0tYy-kBuO:-KOF-ZlpYKSL_PapHBVf:1913178689) ([raw file](https://github.com/maidsafe/routing/blob/85fb642d0790a81a30d8795d6efd632f53d719e2/src/peer_manager.rs#L809)):*
> ```Rust
> #[cfg(feature = "use-mock-crust")]
> impl PeerManager {
>     pub fn clear(&mut self) {
> ```

I agree that `clear_caches` was a misnomer, but maybe `clear` is also misleading, as it suggests that the container is emptied. Maybe `remove_connecting_peers`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1122)*

**Comment by afck** [comment]
Reviewed 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1122)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1122)*

**Pull request merged**
