### PR TITLE
WIP Update crustv0.0.60

### PR DESCRIPTION
**Pull request by benjaminbollen**
CRUST API connection_manager::start_listening changed return type to Vec < Port > ;
from routing we still expect Vec < Endpoint > to know on which endpoints we are accepting messages.

Pausing until task taken up;

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/293)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
@ned14 : can you review and comment please; thanks !

**Comment by benjaminbollen** [comment]
https://github.com/maidsafe/routing/pull/299

addressed by above

**Pull request closed without merging**
