### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by ustulation**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/777)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
@dirvine : This is mainly for printing the Routing Table size in fixed intervals so that we don't have to keep scrolling everytime we add/drop a new node in the terminal

**Comment by dirvine** [comment]
As a temp measure then this is OK but I would recommend not keeping it too long. 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/777#-:-K3KPTd5RjXjYh1kQVmx:-2072124729)_

**Pull request merged**
