### PR TITLE
replace owner with owner_sign_public_key

### PR DESCRIPTION
**Pull request by mmoadeli**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/253)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @benjaminbollen

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/sendable.rs, line 28 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/253#-JpTmphhmftDz-znpqgw)** ([raw file](https://github.com/maidsafe/routing/blob/8f3cc7023071136dd05d2ff45eeb360ec2c0dc86/src/sendable.rs#L28)):</sup>
Is this valid as sentinel for instance needs to know the actual owner to validate the data/message. Is the idea we will provide the key and if so how do we get it?  Usually for instance sentinel will get the owner id then ask for the keys to be also downloaded and match them.  If this is just for certain ID types where we can get teh actual public key from them I would see the point, but this trait is to cover all data types so this change would break that. I.e. if we get a bit of structured data we need to know the owner and then get their keys from the network. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/253)

**Comment by maidsafe-highfive** [comment]
Can one of the admins verify this patch?

**Comment by maidsafe-highfive** [comment]
Can one of the admins verify this patch?

**Comment by maidsafe-highfive** [comment]
Can one of the admins verify this patch?

**Comment by mmoadeli** [comment]
According to @dirvine and @Fraser999 said. I revert Sendable to what it was and apply changes asked by Fraser.

**Pull request closed without merging**
