### PR TITLE
refactor/peer_manager: merge the connection info/token containers

### PR DESCRIPTION
**Pull request by afck**
This merges the `connecting_peers`, `connection_token_map` and
`*_connection_info_map` fields into a map that keeps track of the status
of a peer in general.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1067)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
@afck: no appropriate reviewer found, use r? to override

**Comment by maqi** [comment]
*[src/peer_manager.rs, line 447 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1067#-KLLA5n4kVCFJt_U_OU7:-KLLA5n5BIN2cAAsxp4v:-1651329095) ([raw file](https://github.com/maidsafe/routing/blob/a1c72dc31124d6156a61d1061a98bb91fbb9853d/src/peer_manager.rs#L447)):*
> ```Rust
>                 PeerState::CrustConnecting |
>                 PeerState::SearchingForTunnel => {
>                     timestamp.elapsed().as_secs() >= CONNECTION_TIMEOUT_SECS
> ```

when mock_crust used, this means entries having all the above status will be considered as expired immediately?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1067)*

**Comment by maqi** [comment]
*[src/peer_manager.rs, line 423 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1067#-KLLAkPObeZqTYFCCpMS:-KLLAkPObeZqTYFCCpMT:746217877) ([raw file](https://github.com/maidsafe/routing/blob/a1c72dc31124d6156a61d1061a98bb91fbb9853d/src/peer_manager.rs#L423)):*
> ```Rust
>     }
> 
>     // CONNECTION_TIMEOUT_SECS == 0 if use-mock-crust.
> ```

will having a conditional compilation of this function be more explicit?
same to the below function remove_expired

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1067)*

**Comment by madadam** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[src/peer_manager.rs, line 447 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1067#-KLLA5n4kVCFJt_U_OU7:-KLLD5eSmQH78vV5IxrX:1887160324) ([raw file](https://github.com/maidsafe/routing/blob/a1c72dc31124d6156a61d1061a98bb91fbb9853d/src/peer_manager.rs#L447)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> when mock_crust used, this means entries having all the above status will be considered as expired immediately?
</details>
I think that's the point. With mock-crust, the nodes never expire unless you call the `clear_caches` method manually, which then expires all the nodes not already connected (or tunneled).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1067)*

**Comment by afck** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/peer_manager.rs, line 423 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1067#-KLLAkPObeZqTYFCCpMS:-KLLKSiv5z7PWspTqPrx:403409784) ([raw file](https://github.com/maidsafe/routing/blob/a1c72dc31124d6156a61d1061a98bb91fbb9853d/src/peer_manager.rs#L423)):*
<details><summary><i>Previously, maqi wrote…</i></summary>
> will having a conditional compilation of this function be more explicit?
> same to the below function remove_expired
</details>
I agree regarding `insert_state` - done.
But separate versions of `insert_state` would duplicate a lot of code. Not sure about that.

---

*[src/peer_manager.rs, line 447 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1067#-KLLA5n4kVCFJt_U_OU7:-KLLGdu-6XNAvmOtVop7:-113399545) ([raw file](https://github.com/maidsafe/routing/blob/a1c72dc31124d6156a61d1061a98bb91fbb9853d/src/peer_manager.rs#L447)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> I think that's the point. With mock-crust, the nodes never expire unless you call the `clear_caches` method manually, which then expires all the nodes not already connected (or tunneled).
</details>
Exactly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1067)*

**Comment by madadam** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1067)*

**Comment by madadam** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1067)*

**Comment by Fraser999** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r3, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1067)*

**Pull request merged**
