### PR TITLE
MAID-1363 removed wake_up.rs

### PR DESCRIPTION
**Pull request by meholi0207**
Also removed Action::WakeUp

Hey,
I just finished a RUST 4 task. Hope you like it. Should I provide you a Bitcoin address?

Cheers
Meholi

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/677)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @benjaminbollen (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by dirvine** [comment]
Yes please, if you can attach an address here then perfect. If/when merged
then the payment will be made there. Thanks again

On Wed, Sep 9, 2015 at 11:35 PM, meholi0207 <notifications@github.com>
wrote:

> Also removed Action::WakeUp
>
> Hey,
> I just finished a RUST 4 task. Hope you like it. Should I provide you a
> Bitcoin address?
>
> Cheers
> Meholi
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/maidsafe/routing/pull/677
> Commit Summary
>
>    - removed wake_up.rs
>
> File Changes
>
>    - *M* src/action.rs
>    <https://github.com/maidsafe/routing/pull/677/files#diff-0> (1)
>    - *M* src/lib.rs
>    <https://github.com/maidsafe/routing/pull/677/files#diff-1> (1)
>    - *M* src/routing_node.rs
>    <https://github.com/maidsafe/routing/pull/677/files#diff-2> (13)
>    - *D* src/wake_up.rs
>    <https://github.com/maidsafe/routing/pull/677/files#diff-3> (50)
>
> Patch Links:
>
>    - https://github.com/maidsafe/routing/pull/677.patch
>    - https://github.com/maidsafe/routing/pull/677.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maidsafe/routing/pull/677>.
>



-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by dirvine** [comment]
I assigned the task to you(I hope), if you select in progress then again pass on for review (in Jira) then your part of the workflow.

**Comment by benjaminbollen** [comment]
looks good to me

**Comment by benjaminbollen** [comment]
we just need your bitcoin address now!  Thanks a lot and welcome to the SAFE network!

**Comment by meholi0207** [comment]
Hi,

here is the Bitcoin address: 1rZD6U6GZHZBGj6S3porCxsmZynC28qT2

Looking forward to keep working with you guys.

Cheers

**Comment by NickLambert** [comment]
Payment on the way. Many thanks for your help!

**Pull request merged**
