### PR TITLE
Test on droplets - restoring state to compare for routing issue observed on droplets

### PR DESCRIPTION
**Pull request by benjaminbollen**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/715)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @brian-js

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
I have tested this locally on my MacBook, but the problem predominantly shows on the droplet network, and I have not recently run performance tests from my MacBook, so hard to compare.  The network seems to connect. 

This is a guess on whether this can abate the problem reported this morning.  In either case, with upcoming connection management review in routing this needs to be further examined

**Comment by benjaminbollen** [comment]
did it help?

**Comment by brian-js** [comment]
Peter resolved some crust issues and it appears to be ok now. Still to test vaults though.

**Comment by benjaminbollen** [comment]
ok :) so there was not really a reason to merge this then, as it introduces a pile-up of state :).  No worries, we'll address it Monday.

**Comment by brian-js** [comment]
No and yes.

**Comment by Viv-Rajkumar** [comment]
well if we don't need this and peter's fixes worked without this, why don't we just have this reverted before the version bump in routing? @brian-js @benjaminbollen

**Pull request merged**
