### PR TITLE
fix/state_machine: do not drop current state on terminate

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1092)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/state_machine.rs, line 285 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1092#-KMj1iVxMbrlEualAPx9:-KMj1iVyIUcLeL4GfXxv:-500622173) ([raw file](https://github.com/maidsafe/routing/blob/96a7dee9be836d2a450b881bcc1eb912de97235c/src/state_machine.rs#L285)):*
> ```Rust
> 
>     fn terminate(&mut self) {
>         self.is_running = true;
> ```

Shouldn't that be `false`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1092)*

**Comment by madadam** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/state_machine.rs, line 285 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1092#-KMj1iVxMbrlEualAPx9:-KMj21K4rs7--2i2Jjiy:279762120) ([raw file](https://github.com/maidsafe/routing/blob/96a7dee9be836d2a450b881bcc1eb912de97235c/src/state_machine.rs#L285)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Shouldn't that be `false`?
</details>
Oops! :scream: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1092)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/state_machine.rs, line 285 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1092#-KMj1iVxMbrlEualAPx9:-KMj2YLlrnT2QbtDiafW:160362572) ([raw file](https://github.com/maidsafe/routing/blob/96a7dee9be836d2a450b881bcc1eb912de97235c/src/state_machine.rs#L285)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> Oops! :scream: 
</details>
:-D

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1092)*

**Pull request merged**
