### PR TITLE
Cache data in ttl lru cache in line with current routing requirements.

### PR DESCRIPTION
**Pull request by brian-js**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/650)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @benjaminbollen

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
This is much cleaner, my only concern is that we should be able to set a cache per type, so may need setters anyway to let routing know if it should even try a data type (i.e. we won't use structuredData types in cache). So routing needs to know what to cache, apart from that looks much nicer.

**Comment by benjaminbollen** [comment]
Can you consider following points
1. maybe expand the functionality in a cache.rs object
2. make an elegant way of passing in the constructor of routing -> routing_node which types to cache 
3. actually use the functions in RoutingNode::message_received post filter; if the cache.rs has a nice interface that takes &RoutingMessage or a $Content, then the message_received function can remain concise with single (or a few cache lines)

**Comment by benjaminbollen** [comment]
already merging in; but should be continues

**Pull request merged**
