### PR TITLE
Remove unnecessary mut self in client get requests

### LINKED ISSUE #1070: Inconsistent API
https://github.com/maidsafe/routing/blob/master/src/client.rs#L124
`pub fn send_get_request(&mut self,`

is deviant compared to others:
https://github.com/maidsafe/routing/blob/master/src/client.rs#L133
`pub fn send_put_request(&self,` etc,

and the deviation is unnecessary.

### PR DESCRIPTION
**Pull request by andrebeat**
Minor change. Fixes #1070.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1118)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @afck (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by afck** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1118)*

**Comment by afck** [comment]
Thank you!
Please rebase the change on current master. That will also restart the tests.
(Don't know why one of them timed out. I will look into that next week.)

**Comment by andrebeat** [comment]
Rebased. The test also timed out locally (I'm also on OSX). I increased the timeout to wait for the first node to switch to accepting mode, obviously this is not a proper solution but it seems to make the tests work again.

**Comment by afck** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1118)*

**Comment by afck** [comment]
I'm sorry I have to ask you to rebase again!
There's a lot of parallel work going on in routing right now.

**Comment by andrebeat** [comment]
No problem, rebased! 👍

**Pull request merged**
