### PR TITLE
A few documentation additions.

### PR DESCRIPTION
**Pull request by brian-js**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/876)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Looks good to me.
(Nitpick: Should "were" be "we're" twice in acceptors.rs?)

**Comment by brian-js** [comment]
Cheers @afck, I've updated the PR.

**Pull request merged**
