### PR TITLE
fix/core: send ack if client disconnected, and other cleanups

### PR DESCRIPTION
**Pull request by afck**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1033)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by Viv-Rajkumar** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core.rs, line 774 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5PfOD0jHxEvDhEtfO:-KJ5PfOD0jHxEvDhEtfP:-766441728) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L774)):*
> ```Rust
>     }
> 
>     fn check_not_get_node_name(&self, msg: &RoutingMessage) -> Result<(), RoutingError> {
> ```

Considering we only call this fn at one place and we there validate someone with a client restriction doesn't request relocation, isn't it maybe better to change this fn to something which validates and returns Ok for only `Request` or `Ack`? that way all invalid requests if any made by client should get filtered out?

---

*[src/core.rs, line 795 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5R_xuFsuTxXlaUvQZ:-KJ5R_xuFsuTxXlaUvQ_:1097671089) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L795)):*
> ```Rust
>         // original ack was lost in transit
>         if (self.grp_msg_filter.contains(routing_msg) || !routing_msg.src.is_group()) &&
>            self.is_recipient(&routing_msg.dst) {
> ```

Looking at the impl for `is_recipient` where we just check our state as Node and if we are the dst, wouldn't this make the proxy node now send ack's before the client?

---

*[src/core.rs, line 818 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5SEV777rzhCPKZq44:-KJ5SEV8oumWNqyTRw5n:883036034) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L818)):*
> ```Rust
>         match self.state {
>             State::Node => {
>                 if let Err(error) = self.handle_signed_message_for_node(signed_msg) {
> ```

would maybe consider flipping the order here as in one branch for Clients we return the error from this fn for handling the message ourselves and in the current Node branch we return the error from the send fn instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1033)*

**Comment by afck** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/core.rs, line 774 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5PfOD0jHxEvDhEtfO:-KJ5mGkhsYVuXinSHrq5:-1766661925) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L774)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> Considering we only call this fn at one place and we there validate someone with a client restriction doesn't request relocation, isn't it maybe better to change this fn to something which validates and returns Ok for only `Request` or `Ack`? that way all invalid requests if any made by client should get filtered out?
</details>
Good idea! But maybe we should allow `Response`, too, for later use?

---

*[src/core.rs, line 795 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5R_xuFsuTxXlaUvQZ:-KJ5mW3vx5RgEr_PqIqX:287921785) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L795)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> Looking at the impl for `is_recipient` where we just check our state as Node and if we are the dst, wouldn't this make the proxy node now send ack's before the client?
</details>
Right, that was a bug! I fixed the `is_recipient` implementation.

---

*[src/core.rs, line 818 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5SEV777rzhCPKZq44:-KJ5o8TaghGSxBmcOFJk:-499146009) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L818)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> would maybe consider flipping the order here as in one branch for Clients we return the error from this fn for handling the message ourselves and in the current Node branch we return the error from the send fn instead
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1033)*

**Comment by Viv-Rajkumar** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core.rs, line 774 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5PfOD0jHxEvDhEtfO:-KJ5xwoTQOFfNqKJXere:907341759) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L774)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Good idea! But maybe we should allow `Response`, too, for later use?
</details>
yeh but we don't even expose sending `Response` type message via `client.rs` so why facilitate that already here

---

*[src/core.rs, line 853 \[r3\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5wkU2vaCL-HK-CxJU:-KJ5wkU3k1-8vx4XXU_L:-13658966) ([raw file](https://github.com/maidsafe/routing/blob/150993008ec70872e08d6a04513d01cd670f529c/src/core.rs#L853)):*
> ```Rust
>         self.add_to_cache(routing_msg);
> 
>         if self.signed_message_filter.count(signed_msg) <= 1 &&
> ```

can this ever be `< 1` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1033)*

**Comment by afck** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/core.rs, line 774 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5PfOD0jHxEvDhEtfO:-KJ5zSNvbLhV1ktcFxh1:-499146009) ([raw file](https://github.com/maidsafe/routing/blob/33803e96d658f31b8e0a046de89ed93e13ad05ee/src/core.rs#L774)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> yeh but we don't even expose sending `Response` type message via `client.rs` so why facilitate that already here
</details>
Done.

---

*[src/core.rs, line 853 \[r3\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5wkU2vaCL-HK-CxJU:-KJ5zaOBLNEYAaBIeZVe:-499146009) ([raw file](https://github.com/maidsafe/routing/blob/150993008ec70872e08d6a04513d01cd670f529c/src/core.rs#L853)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> can this ever be `< 1` ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1033)*

**Comment by Viv-Rajkumar** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core.rs, line 824 \[r4\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5zF2uHcloY20bbzuX:-KJ5zF2uHcloY20bbzuY:-1184506229) ([raw file](https://github.com/maidsafe/routing/blob/f7582707d3db5212daf3968152a1eea1900b6235/src/core.rs#L824)):*
> ```Rust
>             State::Node => {
>                 if let Err(error) = self.send(signed_msg, route, hop_name, sent_to) {
>                     error!("{:?} Failed to send {:?}: {:?}", self, signed_msg, error);
> ```

Maybe `error!` is a bit aggressive considering we could have got this error because we havent handled the event yet from crust?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1033)*

**Comment by afck** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/core.rs, line 824 \[r4\]](https://reviewable.io:443/reviews/maidsafe/routing/1033#-KJ5zF2uHcloY20bbzuX:-KJ6LXyvWPJyhw7rEKgN:-499146009) ([raw file](https://github.com/maidsafe/routing/blob/f7582707d3db5212daf3968152a1eea1900b6235/src/core.rs#L824)):*
<details><summary><i>Previously, Viv-Rajkumar (Viv Rajkumar) wrote…</i></summary>
> Maybe `error!` is a bit aggressive considering we could have got this error because we havent handled the event yet from crust?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1033)*

**Comment by Viv-Rajkumar** [comment]
Reviewed 2 of 4 files at r3, 1 of 2 files at r4, 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1033)*

**Pull request merged**
