### PR TITLE
enable env_logger for routing example

### PR DESCRIPTION
**Pull request by benjaminbollen**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/538)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
@rossmuir  @Fraser999  Can you please check Windows CI seems to have not found cargo ?

**Comment by rossmuir** [comment]
@dirvine the jenkins slave had issues - successfully rerun.

**Pull request merged**
