### PR TITLE
Minor fixups

### PR DESCRIPTION
**Pull request by canndrew**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/776)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @brian-js

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Reviewed 5 of 6 files at r1.
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/utils.rs, line 25 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/776#-K3JwQssZiRGHRzdBIUK)** ([raw file](https://github.com/maidsafe/routing/blob/c248014bbb932322675e3d1773c441e2a01b0d36/src/utils.rs#L25)):</sup>
Not sure about this Andrew, can you explain it a little bit please (my ignorance) 


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/776)

**Comment by dirvine** [comment]
Reviewed 1 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/776)

**Comment by dirvine** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[src/utils.rs, line 25 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/776#-K3JwQssZiRGHRzdBIUK)** ([raw file](https://github.com/maidsafe/routing/blob/c248014bbb932322675e3d1773c441e2a01b0d36/src/utils.rs#L25)):</sup>
Ah nice one, thanks Andrew


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/776)

**Pull request merged**
