### PR TITLE
refactor/node-state: simplify use of peer manager in node state

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1123)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/peer_manager.rs, line 162 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOonbqtfERqzT3ETQj:-KOOonbrZ7Nvxtj__zHu:bpzgwc4) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/peer_manager.rs#L162)):*
> ```Rust
>         match self.state {
>             PeerState::Client(ref pub_key) => pub_key,
>             PeerState::JoiningNode(ref pub_key) => pub_key,
> ```

Clippy is not amused: `this `match` has identical arm bodies`

---

*[src/peer_manager.rs, line 522 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOpeXRUNBiaFvPRMY9:-KOOpeXRUNBiaFvPRMYA:byj89zk) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/peer_manager.rs#L522)):*
> ```Rust
>     }
> 
>     pub fn get_connected_peer(&self, peer_id: &PeerId) -> Option<&Peer> {
> ```

Let's strive for documenting all new public items, even if they are not exported from the crate.

---

*[src/states/node.rs, line 1651 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOtHQjf3TTxemJNdyN:-KOOtHQkSSqU8iBGUqLS:b5r70qp) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/states/node.rs#L1651)):*
> ```Rust
> 
>         if let Some(details) = dropped_node_details {
>             if !self.dropped_routing_node(*peer.name(), details) {
> ```

So ... `dropped_routing_node` returns `false` if we have to disconnect, does it? A short doc comment for that and `dropped_peer`'s return values would make this a lot easier to understand.

---

*[src/states/node.rs, line 1671 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOuBzC1ANJr2u2FymF:-KOOuBzDCObpTNGqLA3Q:btiqr1s) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/states/node.rs#L1671)):*
> ```Rust
>                        peer.name(),
>                        peer_id);
>                 self.send_event(Event::Terminate);
> ```

If my reading is correct, we'll end up here if we lost our proxy node which hasn't transitioned into our routing table yet - but in a large network the proxy node is likely to never do that and at some point will drop us. I guess this needs a check for whether the routing table has `GROUP_SIZE` entries.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1123)*

**Comment by madadam** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/peer_manager.rs, line 162 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOonbqtfERqzT3ETQj:-KOOwUEwUZN4f3_ghtyw:b-lqzqh5) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/peer_manager.rs#L162)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Clippy is not amused: `this `match` has identical arm bodies`
</details>
Right. Actually, why do we even need to keep those pub_keys as members in there? Are they ever different from `pub_id.signing_public_key`? If not, we can get rid of this method (or at least simplify it to a one-liner).

---

*[src/states/node.rs, line 1671 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOuBzC1ANJr2u2FymF:-KOOx2Iifs7yS8qiadcK:bissvuk) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/states/node.rs#L1671)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> If my reading is correct, we'll end up here if we lost our proxy node which hasn't transitioned into our routing table yet - but in a large network the proxy node is likely to never do that and at some point will drop us. I guess this needs a check for whether the routing table has `GROUP_SIZE` entries.
</details>
So terminate only if routing table size is < `GROUP_SIZE`, correct?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1123)*

**Comment by afck** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/peer_manager.rs, line 162 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOonbqtfERqzT3ETQj:-KOOxwMHNk1mZkEkp8m4:bx93oez) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/peer_manager.rs#L162)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> Right. Actually, why do we even need to keep those pub_keys as members in there? Are they ever different from `pub_id.signing_public_key`? If not, we can get rid of this method (or at least simplify it to a one-liner).
</details>
You're right, since `Peer` contains that now anyway, it doesn't need to be in `PeerState` anymore. :+1: 
We just need to make sure that if a client joins the routing table, we update their name. (I.e. use the new ID from the `NodeIdentify` message.)

---

*[src/states/node.rs, line 1671 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/1123#-KOOuBzC1ANJr2u2FymF:-KOOyWavq21zGwYbYppT:bgzdc3x) ([raw file](https://github.com/maidsafe/routing/blob/8be5421d754964387d75d6bc8bfa1a0670ed3157/src/states/node.rs#L1671)):*
<details><summary><i>Previously, madadam (Adam Cigánek) wrote…</i></summary>
> So terminate only if routing table size is < `GROUP_SIZE`, correct?
</details>
Yes, I think that's a reasonable criterion for now.
(It will probably change with the Disjoint Nodes feature, though.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1123)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1123)*

**Pull request merged**
