### PR TITLE
Needed correction to updated Authority 

### PR DESCRIPTION
**Pull request by benjaminbollen**
Needed correction to updated Authority definitions as it the introduction of OurCloseGroup had broken NaeManager, and as such broke the PutPublicId; 

Corrected by additional condition on Nae is from_group != destination  (because the OurCloseGroup is purely for group-to-group) (not from a single node)

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/364)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by benjaminbollen** [comment]
resolves #359

**Comment by dirvine** [comment]
r? @dirvine

---

Review status: 0 of 1 files reviewed, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/364)

**Comment by dirvine** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/authority.rs, line 103 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/364#-JrcGUVjhBd-OtCRosG7)** ([raw file](https://github.com/maidsafe/routing/blob/3878d8fe582a713d7aa4c5d6c14f28802ea5abe6/src/authority.rs#L103)):</sup>
is the clone() needed here ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/364)

**Comment by benjaminbollen** [comment]
Review status: 0 of 1 files reviewed, 1 unresolved discussion, some commit checks pending.

---

<sup>**[src/authority.rs, line 103 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/364#-JrcGUVjhBd-OtCRosG7)** ([raw file](https://github.com/maidsafe/routing/blob/3878d8fe582a713d7aa4c5d6c14f28802ea5abe6/src/authority.rs#L103)):</sup>
it's ugly, the pretty way is matching the from_group, but I was rushing; now that I now this has done the trick I'll clean it up, takes two seconds

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/364)

**Comment by dirvine** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- src/authority.rs @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/364)

**Pull request merged**
