### PR TITLE
RoutingTable tests cleanup

### PR DESCRIPTION
**Pull request by Fraser999**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/814)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/routing_table.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cEN7iAFFr5WrAp-Yr:-K4cEN7iAFFr5WrAp-Ys:-454779258) ([raw file](https://github.com/maidsafe/routing/blob/2f285dff752a9c74ab336ec6c2fa4f168a39f597/src/routing_table.rs#L48)):*
I am not sure of this or the self.sorter() can you describe what you are doing here a bit more and specifically if you think it makes code simpler or not. To me this may appear more tricky 

---

*[src/routing_table.rs, line 205 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cDKo7ktleXzQBLmuu:-K4cDKo7ktleXzQBLmuv:1340845010) ([raw file](https://github.com/maidsafe/routing/blob/2f285dff752a9c74ab336ec6c2fa4f168a39f597/src/routing_table.rs#L205)):*
does this require iter() I think find() is cool on vector 

---

*[src/routing_table.rs, line 223 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cDu4qZ1EKY6Xhc8Rb:-K4cDu4qZ1EKY6Xhc8Rc:677880290) ([raw file](https://github.com/maidsafe/routing/blob/31154713268535012d8061909f4f403611a08278/src/routing_table.rs#L223)):*
nice

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/814)*

**Comment by Fraser999** [comment]
*[src/routing_table.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cEN7iAFFr5WrAp-Yr:-K4cH9xImtDyaFurdiT8:-883653863) ([raw file](https://github.com/maidsafe/routing/blob/2f285dff752a9c74ab336ec6c2fa4f168a39f597/src/routing_table.rs#L48)):*
It's just a function which returns a predicate which can be used to sort a vector of NodeInfos.  I actually commented this at some stage, but have obviously lost the comment when I moved the function.

It was surprisingly difficult to create a predicate for this, but there seems to be a few pending changes to Rust which will drastically simplify this. For now, holding the predicate in a Box is the best option I think.

When I started this part, I was looking to remove the several places where we repeated the 5 or so lines of closure function at each sort location (mostly in the tests).  I then found out that the tests are more often sorting a collection of NameTypes than NodeInfos, so there's a similar function down in the test mod.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/814)*

**Comment by Fraser999** [comment]
*[src/routing_table.rs, line 205 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cDKo7ktleXzQBLmuu:-K4cIwwz9PF9uR3Ko_nM:-149304963) ([raw file](https://github.com/maidsafe/routing/blob/2f285dff752a9c74ab336ec6c2fa4f168a39f597/src/routing_table.rs#L205)):*
Yes - it needs the iter() unfortunately.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/814)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/routing_table.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cEN7iAFFr5WrAp-Yr:-K4cLEEDsCHuOiTAPJ8M:1287686204) ([raw file](https://github.com/maidsafe/routing/blob/2f285dff752a9c74ab336ec6c2fa4f168a39f597/src/routing_table.rs#L48)):*
Is this not then only used in one function here that created the predicate in place. I am not sure this removes complexity but perhaps forces heap allocation where maybe rust can optimise an in place predicate ? 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/814)*

**Comment by Fraser999** [comment]
*[src/routing_table.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cEN7iAFFr5WrAp-Yr:-K4cNocC1WZR7bz3k0Dl:-912774144) ([raw file](https://github.com/maidsafe/routing/blob/2f285dff752a9c74ab336ec6c2fa4f168a39f597/src/routing_table.rs#L48)):*
I've used it to initialise the sorter member of RT and also in the target_nodes function.  It was originally being used in a couple of test cases too, but after looking further, I realised that the tests didn't need to be sorting the vector so those uses have been removed.

I'm not sure about the performance hit if any, but I feel the code is slightly cleaner with this since we're not duplicating closures.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/814)*

**Comment by dirvine** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/routing_table.rs, line 48 \[r1\]](https://reviewable.io:443/reviews/maidsafe/routing/814#-K4cEN7iAFFr5WrAp-Yr:-K4cSdVBj1rHrzWnPRi8:-161479574) ([raw file](https://github.com/maidsafe/routing/blob/2f285dff752a9c74ab336ec6c2fa4f168a39f597/src/routing_table.rs#L48)):*
Are you saying this is used in more than one place and so is the sorter? I need to look more at the whole file now I think 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/814)*

**Comment by dirvine** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/814)*

**Pull request merged**
