### PR TITLE
updated crust to 0.5.0 and fixed some changes in std

### PR DESCRIPTION
**Pull request by waynenilsen**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/767)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @canndrew (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by waynenilsen** [comment]
Sorry for the not-so-good commit message, I thought that I had already committed once for the lib changes and then once for the test changes but it turns out that was not the case. This just updates crust and silents some lints. I will make line comments for the more contentious changes

**Comment by waynenilsen** [comment]
also, didn't realize but it looks like someone else did this already

**Comment by Viv-Rajkumar** [comment]
https://github.com/maidsafe/routing/pull/769 should hopefully address this. Please do reopen this PR if still needed

**Comment by waynenilsen** [comment]
probably the changes to `sleep_ms` should be integrated, this will cause build failure with the latest nightly due to deprecation in `std`

**Comment by Viv-Rajkumar** [comment]
they are with https://github.com/maidsafe/routing/commit/2863b1fe00ffdd097cbd56e544373ad27fcd874b I guess. `master` branch against latest nightly seems to build fine https://travis-ci.org/maidsafe/routing

**Comment by waynenilsen** [comment]
:+1:

**Pull request closed without merging**
