### PR TITLE
Export mock crust so upper layers can use it too

### PR DESCRIPTION
**Pull request by madadam**
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/951)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @canndrew

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mock_crust/crust.rs, line 18 \[r3\]](https://reviewable.io:443/reviews/maidsafe/routing/951#-KEFhyaY77Ib-z7X7vXB:-KEFhyaY77Ib-z7X7vXC:-960913163) ([raw file](https://github.com/maidsafe/routing/blob/f2f4fc0ad7e7adaa60a5fb8ca0562a120cb861a4/src/mock_crust/crust.rs#L18)):*
If they are exported now, these methods should probably be documented.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/951)*

**Comment by madadam** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/mock_crust/crust.rs, line 18 \[r3\]](https://reviewable.io:443/reviews/maidsafe/routing/951#-KEFhyaY77Ib-z7X7vXB:-KEFogZ_2bke9X4zivgB:-499146009) ([raw file](https://github.com/maidsafe/routing/blob/f2f4fc0ad7e7adaa60a5fb8ca0562a120cb861a4/src/mock_crust/crust.rs#L18)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/951)*

**Comment by afck** [comment]
Reviewed 2 of 4 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/951)*

**Pull request merged**
