### PR TITLE
Maid 1105 refresh routing table

### PR DESCRIPTION
**Pull request by benjaminbollen**

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @inetic

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by inetic** [comment]
OK with me, OK with you Ben?

**Comment by benjaminbollen** [comment]
yes, indeed, will make that change.

**Comment by benjaminbollen** [comment]
@inetic thanks for your input.  If you merge, Ross will review and test routing v0.1.5

**Pull request merged**
