### PR TITLE
feat/routing table: added disjoint groups routing table to crate

### PR DESCRIPTION
**Pull request by Fraser999**
This new routing table is still unused and untested within the crate.

---
This change is [Reviewable](https://reviewable.io/reviews/maidsafe/routing/1144)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @afck

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by afck** [comment]
Reviewed 53 of 58 files at r1.
Review status: 53 of 58 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1144)*

**Comment by afck** [comment]
The commit message should say "add", not "added.".

---

Reviewed 5 of 58 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[src/routing_table/mod.rs, line 74 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6XcuF3xbON4Nl2gGy:-KS6XcuF3xbON4Nl2gGz:b-miorru) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L74)):*
> ```Rust
> // * If the destination is the address of a node, the message will reach that node after at most
> //   `B - 1` hops.
> // * Otherwise, if the destination is a `k`-close group with `k <= bucket_size`, the message will
> ```

That should probably just be `close group` now, without the `k`.

---

*[src/routing_table/mod.rs, line 91 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6Xri0-Y8l4s1pBjAf:-KS6Xri1gda7DDbyEQYM:b-1epn5z) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L91)):*
> ```Rust
> //
> // > Whenever a bucket `n` has fewer than `bucket_size` entries, it contains *all* nodes in the
> // > network with bucket distance `B - n`.
> ```

That should be updated to the new invariant.

---

*[src/routing_table/mod.rs, line 100 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6Y-8f0NmF10YBDoW6:-KS6Y-8gJt6ySSLgL9xf:bdmw42n) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L100)):*
> ```Rust
> //
> // The sender may choose to send a message via up to `bucket_size` distinct paths to provide
> // redundancy against malfunctioning hop nodes. These paths are likely, but not guaranteed, to be
> ```

They are now guaranteed to be disjoint.

---

*[src/routing_table/mod.rs, line 372 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6d_CGFpNQU7mJMv2Z:-KS6d_CHjA82ooRR5oqa:b-8nz7gc) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L372)):*
> ```Rust
>                 assert!(self.groups.insert(new_prefix, group2).is_none());
>             } else {
>                 assert!(result.is_empty());
> ```

Please remove the three `assert!`s.

---

*[src/routing_table/mod.rs, line 443 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6j4r3Xs8UoXKIDRrE:-KS6j4r46dfbMQz__81A:bm4abk8) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L443)):*
> ```Rust
>         let other_details = OtherMergeDetails {
>             prefix: merge_details.prefix,
>             group: unwrap!(self.groups.get(&merge_details.prefix)).clone(),
> ```

Shouldn't this include the `needed` contacts in that group? Other groups need to connect to them, too, regardless of whether we ourselves have already established a connection?

---

*[src/routing_table/mod.rs, line 459 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6k28C_plkCQPxIy9W:-KS6k28C_plkCQPxIy9X:b-tyyq96) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L459)):*
> ```Rust
>         // Establish list of provided contacts which are currently missing from our table.
>         let existing_names =
>             self.groups.iter().flat_map(|(_, names)| names.iter()).collect::<HashSet<_>>();
> ```

Do we really need _all_ groups here? After the `merge` call, wouldn't it suffice to just use the merged group for the `difference` call?

---

*[src/routing_table/mod.rs, line 552 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6mrX4irmU6ovCaDCb:-KS6mrX4irmU6ovCaDCc:b-7dj0k5) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L552)):*
> ```Rust
>             .flat_map(|(_, names)| names.into_iter())
>             .collect::<HashSet<_>>();
>         assert!(groups.insert(*new_prefix, merged_names).is_none());
> ```

Another `assert!`.

---

*[src/routing_table/mod.rs, line 586 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6nRCjio1TtoiX1jVw:-KS6nRCkQYbEBVnvI85Z:b-ukykjv) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L586)):*
> ```Rust
>         keys.sort_by(|&lhs, &rhs| lhs.cmp_distance(rhs, name));
>         *keys[0]
>     }
> ```

Should these two methods really copy/clone internally? Or should they return a reference?

---

*[src/routing_table/mod.rs, line 617 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6oBZyTJXnFf4WoQZO:-KS6oBZyTJXnFf4WoQZP:b-lkr984) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L617)):*
> ```Rust
>                 "\t},"
>             };
>             try!(writeln!(formatter, "{}", comma));
> ```

Since there's a format string anyway, it might be less confusing to put the `\t}` in there.

---

*[src/routing_table/prefix.rs, line 168 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6WnW1klWqvAujHhul:-KS6WnW1klWqvAujHhum:bse6sq8) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/prefix.rs#L168)):*
> ```Rust
>         assert!(!str_to_prefix(b"1010").is_compatible(&str_to_prefix(b"1011")));
>         // assert_eq!(3, str_to_prefix(b"1010").common_prefix(&str_to_prefix(b"1011"))); // 101
>         // assert_eq!(3, str_to_prefix(b"101").common_prefix(&str_to_prefix(b"1011"))); // 101
> ```

Do these still need to be commented out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1144#-:-KS6U38nIpCRCRobZiYq:b9rivg)*

**Comment by Fraser999** [comment]
Review status: 56 of 58 files reviewed at latest revision, 10 unresolved discussions.

---

*[src/routing_table/mod.rs, line 443 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6j4r3Xs8UoXKIDRrE:-KSAjBMcPnqBCNGY7sSm:b6zrrkh) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L443)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Shouldn't this include the `needed` contacts in that group? Other groups need to connect to them, too, regardless of whether we ourselves have already established a connection?
</details>
Good catch.

---

*[src/routing_table/mod.rs, line 459 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6k28C_plkCQPxIy9W:-KSAl6NsjcIy-a2pNTVm:bvuaaz7) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L459)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Do we really need _all_ groups here? After the `merge` call, wouldn't it suffice to just use the merged group for the `difference` call?
</details>
Again, good point :)

---

*[src/routing_table/mod.rs, line 586 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6nRCjio1TtoiX1jVw:-KSArE6OntPNJKqC1ODB:burv0cy) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L586)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Should these two methods really copy/clone internally? Or should they return a reference?
</details>
For `find_group_prefix()` there are borrowing issues associated with `self` if returning a reference, but I'll change `closest_group_prefix()` as suggested.

---

*[src/routing_table/prefix.rs, line 168 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6WnW1klWqvAujHhul:-KSAsmtedSVMlrAsHon0:br6rrro) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/prefix.rs#L168)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> Do these still need to be commented out?
</details>
Nope :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1144)*

**Comment by afck** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/routing_table/mod.rs, line 74 at r1](https://reviewable.io:443/reviews/maidsafe/routing/1144#-KS6XcuF3xbON4Nl2gGy:-KSAumC7Skwd8o0kRDA9:bsfei5r) ([raw file](https://github.com/maidsafe/routing/blob/d0df2a718454bde96304e93952e93b464d407970/src/routing_table/mod.rs#L74)):*
<details><summary><i>Previously, afck (Andreas Fackler) wrote…</i></summary>
> That should probably just be `close group` now, without the `k`.
</details>
(Let's update docs in a separate PR, as discussed.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1144)*

**Comment by afck** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/maidsafe/routing/1144)*

**Pull request merged**
