### PR TITLE
Add a Lines of Code badge

### PR DESCRIPTION
**Pull request by willief**
issue #1762

### CODE REVIEW

**Comment by S-Coyle** [comment]
@willief As you mentioned in the issue raised for this, tokei.rs seems to be down at the moment. Note that this has been added into the SCL repository (https://github.com/maidsafe/safe_client_libs#safe_client_libs) earlier this year. It would be good to know that it was stable before we started adding it to more repositories. I'll check up on it daily to see if it's up and it stays up before deciding whether to approve or close this PR.

**Comment by willief** [comment]
Yes, shame tokei.rs is down. I had been meaning to submit LoC PRs for all projects but decided just to submit this one until we see if its a temporary blip or if tokei.rs is no more.
I think there are other LoC providers but have not looked too hard yet.
So, yes, fully agree, lets leave this one for a while the tokei.rs status becomes clearer.

**Comment by willief** [comment]
> @willief As you mentioned in the issue raised for this, tokei.rs seems to be down at the moment. Note that this has been added into the SCL repository (https://github.com/maidsafe/safe_client_libs#safe_client_libs) earlier this year. 


Yes that was me under a different GitHub persona.    No longer appropriate for me to use the trecement account.

**Comment by S-Coyle** [comment]
Seems tokei.rs has been back up the last few days so at least we know it's not permanently down - I think let's leave it for another week or so and if it remains stable during that time then we can go ahead & merge (I'm checking its status daily)

**Comment by willief** [comment]
its been up - it's been down...   I agree, lets leave it until we see how stable it remains.

**Comment by willief** [comment]
Yes indeed, @S-Coyle  what seems like a trivial wee enhancement can easily turn into a maintenance nightmare.  As you say this is probably  best suited for the larger "flagship" repos only.

**Pull request merged**
