### PR TITLE
test connection lost

### PR DESCRIPTION
**Pull request by mmoadeli**
tests connection lost. There seem to be a bug in crust which causes connection to be disconnected immediately after it is established.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/237)

### CODE REVIEW

**Comment by dirvine** [comment]
It will be good to let @chandraprakash  and @Fraser999  take a look here Mahmoud as the CRUST tests do not show this behaviour (of disconnecting). Thx though nice work

**Comment by dirvine** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- src/routing_node.rs @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/237)

**Comment by maidsafe-highfive** [comment]
Can one of the admins verify this patch?

**Comment by maidsafe-highfive** [comment]
Can one of the admins verify this patch?

**Comment by maidsafe-highfive** [comment]
Can one of the admins verify this patch?

**Comment by dirvine** [comment]
@mmoadeli  Can you please confirm you still want this PR and if so please look at conflicts.

**Comment by mmoadeli** [comment]
@dirvine This is the PR which you asked to be stopped as it had some issues, mainly the fact that it does not conform to the real use case, where each routing node is run as one process. Therefore, I close it.

**Pull request closed without merging**
