### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by dirvine**
Several commits. The one to check is removal of floats in calculations as this will switch to integer calcs and may need some further analysis.

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/routing/812)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @brian-js

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/types.rs, line 66 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/812#-K4aYG5rVKjzYVlyTuAu:-K4aYG5rVKjzYVlyTuAv:736437463) ([raw file](https://github.com/maidsafe/routing/blob/3cc2ac363deda163450d5eca09d135484232ad68/src/types.rs#L66)):*
wouldn't this always be 0

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/812)*

**Comment by dirvine** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/types.rs, line 66 \[r2\]](https://reviewable.io:443/reviews/maidsafe/routing/812#-K4aYG5rVKjzYVlyTuAu:-K4bKU0Yu4robQmBrgc5:557100609) ([raw file](https://github.com/maidsafe/routing/blob/3cc2ac363deda163450d5eca09d135484232ad68/src/types.rs#L66)):*
Yes it would :) cheers Spandan, we should check this or set precision, I have reverted and will look for a more secure "fix". for now this is OK though,

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/routing/812)*

**Pull request merged**
